name: Feature/Enhancement
description: Request a new feature or enhancement.
title: 'Feature/Enhancement: [Short Description]'
body:
  - type: markdown
    attributes:
      value: |
        All features and enhancements require the below information to be completed. Incomplete issues will be closed.
  - type: input
    id: description
    attributes:
      label: Description
      placeholder: Describe the feature/enhancement.
  - type: input
    id: expected_behaviour
    attributes:
      label: Expected Behaviour
      placeholder: Describe the expected behaviour of the new feature/enhancement.
  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      placeholder: Document the proposed solution for the new feature/enhancement.